[workspace]
resolver = "2"
members = [
    "crates/sidewire-protocol",
    "apps/sidewire",
    "apps/sidewired",
]

[workspace.package]
version = "0.9.5"
edition = "2024"
license = "GPL-3.0-only"
authors = ["SideWire contributors"]

[workspace.dependencies]
anyhow = "1"
blake3 = "1"
clap = { version = "4", features = ["derive"] }
postcard = { version = "1", features = ["alloc"] }
rand = "0.9"
serde = { version = "1", features = ["derive"] }
snow = "0.9"
spake2 = "0.4"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[profile.release]
panic = "abort"
lto = "thin"
codegen-units = 1
