import fs from 'node:fs';
const p='C:/Users/Administrator/Documents/Dev/Rust/SideWire-KernelSU/apps/sidewire/src/main.rs';
let s=fs.readFileSync(p,'utf8');
s=s.replace('async fn run_exec_client(\n    control: &str,\n    device: Option<String>,\n    program: String,', 'async fn run_exec_client(\n    control: &str,\n    device: Option<String>,\n    run_as: RunAs,\n    program: String,');
s=s.replace('        cwd: None,\n    };', '        cwd: None,\n        run_as,\n    };');
s=s.replace('async fn shell_exec(control: &str, device: Option<String>, cwd: Option<String>, command: &str)', 'async fn shell_exec(control: &str, device: Option<String>, run_as: RunAs, cwd: Option<String>, command: &str)');
s=s.replace('        cwd,\n    };\n    request_control(control, &request).await\n}\n\nasync fn run_shell(control: &str, device: Option<String>)', '        cwd,\n        run_as,\n    };\n    request_control(control, &request).await\n}\n\nasync fn run_shell(control: &str, device: Option<String>, run_as: RunAs)');
s=s.replaceAll('shell_exec(control, device.clone(), None, "id -u")', 'shell_exec(control, device.clone(), run_as, None, "id -u")');
s=s.replaceAll('shell_exec(control, device.clone(), Some(cwd.clone()),', 'shell_exec(control, device.clone(), run_as, Some(cwd.clone()),');
fs.writeFileSync(p,s);
