import fs from 'node:fs';
const p='C:/Users/Administrator/Documents/Dev/Rust/SideWire-KernelSU/apps/sidewire/src/main.rs';
let s=fs.readFileSync(p,'utf8');
s=s.replace('use clap::{Parser, Subcommand};','use clap::{Parser, Subcommand, ValueEnum};');
s=s.replace('ExecExit, ExecRequest, FrameKind, Hello, HelloAck, decode, frame, read_frame, write_frame,','ExecExit, ExecIdentity, ExecRequest, FrameKind, Hello, HelloAck, decode, frame, read_frame, write_frame,');
if(!s.includes('enum RunAs')) s=s.replace('const DEFAULT_CONTROL: &str = "127.0.0.1:58322";','const DEFAULT_CONTROL: &str = "127.0.0.1:58322";\n\n#[derive(Clone, Copy, Debug, ValueEnum, Serialize, Deserialize)]\nenum RunAs { Root, Shell }\nimpl From<RunAs> for ExecIdentity { fn from(v: RunAs) -> Self { match v { RunAs::Root => Self::Root, RunAs::Shell => Self::Shell } } }');
s=s.replace('        program: String,\n        args: Vec<String>,\n    },\n    Shell {','        #[arg(long = "as", value_enum, default_value = "root")]\n        run_as: RunAs,\n        program: String,\n        args: Vec<String>,\n    },\n    Shell {');
s=s.replace('        #[arg(short = \'s\', long)]\n        device: Option<String>,\n    },\n}', '        #[arg(short = \'s\', long)]\n        device: Option<String>,\n        #[arg(long = "as", value_enum, default_value = "root")]\n        run_as: RunAs,\n    },\n}');
s=s.replace('        args: Vec<String>,\n        cwd: Option<String>,','        args: Vec<String>,\n        cwd: Option<String>,\n        run_as: RunAs,');
s=s.replace('            program,\n            args,\n        } => run_exec_client(&control, device, program, args).await,\n        Command::Shell { control, device } => run_shell(&control, device).await,','            run_as,\n            program,\n            args,\n        } => run_exec_client(&control, device, run_as, program, args).await,\n        Command::Shell { control, device, run_as } => run_shell(&control, device, run_as).await,');
s=s.replace('            args,\n            cwd,\n        } =>', '            args,\n            cwd,\n            run_as,\n        } =>');
s=s.replace('remote_exec(&session, program, args, cwd)', 'remote_exec(&session, program, args, cwd, run_as)');
s=s.replace('    cwd: Option<String>,\n) -> Result<(String, String, Option<i32>)> {', '    cwd: Option<String>,\n    run_as: RunAs,\n) -> Result<(String, String, Option<i32>)> {');
s=s.replace('        cwd,\n    };', '        cwd,\n        identity: run_as.into(),\n    };');
fs.writeFileSync(p,s);
