import fs from 'node:fs';
const p='apps/sidewired/src/main.rs';
let s=fs.readFileSync(p,'utf8');
s=s.replace(/\n\s*#\[cfg\(target_os = "android"\)\]\n\s*enter_daemon_context\(\)\?;/,'');
const a=s.indexOf('fn apply_identity(');
const b=s.indexOf('\nasync fn handle_exec',a);
if(a<0||b<0) throw new Error('identity block not found');
const block=`fn apply_identity(command: &mut Command, identity: ExecIdentity) -> Result<()> {\n    if matches!(identity, ExecIdentity::Root) { return Ok(()); }\n    #[cfg(target_os = "android")]\n    unsafe {\n        command.pre_exec(|| {\n            set_exec_context("u:r:shell:s0")?;\n            const GROUPS: [libc::gid_t; 15] = [1004,1007,1011,1015,1028,1078,1079,2000,3001,3002,3003,3006,3009,3011,3012];\n            if libc::setgroups(GROUPS.len(), GROUPS.as_ptr()) != 0 { return Err(std::io::Error::last_os_error()); }\n            if libc::setgid(2000) != 0 { return Err(std::io::Error::last_os_error()); }\n            if libc::setuid(2000) != 0 { return Err(std::io::Error::last_os_error()); }\n            Ok(())\n        });\n    }\n    #[cfg(not(target_os = "android"))]\n    { let _ = command; }\n    Ok(())\n}\n\n#[cfg(target_os = "android")]\nfn set_exec_context(context: &str) -> std::io::Result<()> {\n    use std::ffi::CString;\n    let value=CString::new(context).map_err(|_| std::io::Error::new(std::io::ErrorKind::InvalidInput,"invalid SELinux context"))?;\n    let fd=unsafe { libc::open(c"/proc/self/attr/exec".as_ptr(), libc::O_WRONLY | libc::O_CLOEXEC) };\n    if fd < 0 { return Err(std::io::Error::last_os_error()); }\n    let bytes=value.as_bytes_with_nul();\n    let rc=unsafe { libc::write(fd, bytes.as_ptr().cast(), bytes.len()-1) };\n    let saved=if rc<0 {Some(std::io::Error::last_os_error())} else {None};\n    unsafe { libc::close(fd); }\n    if let Some(e)=saved { return Err(e); }\n    Ok(())\n}\n`;
s=s.slice(0,a)+block+s.slice(b);
fs.writeFileSync(p,s);
