import fs from 'node:fs';
const p='apps/sidewired/src/main.rs';
let s=fs.readFileSync(p,'utf8');
s=s.replace('    ExecExit, ExecIdentity, ExecRequest, FrameKind, HelloAck, decode, frame, raw_frame, read_frame,\n    write_frame,','    ExecExit, ExecIdentity, ExecRequest, FileMeta, FilePullRequest, FilePushRequest, FrameKind,\n    HelloAck, ProxyStartAck, ProxyStartRequest, ProxyTokenMode, decode, frame, raw_frame, read_frame,\n    write_frame,');
s=s.replace('use std::{fs, process::Stdio};','use std::{collections::HashMap, fs, process::Stdio};');
s=s.replace('use tokio::{\n    net::{TcpListener, TcpStream},','use tokio::{\n    fs::File,\n    io::{AsyncReadExt, AsyncWriteExt},\n    net::{TcpListener, TcpStream},');
s=s.replace('async fn serve(mut stream: TcpStream, name: &str, inbound: bool) -> Result<()> {','async fn serve(mut stream: TcpStream, name: &str, inbound: bool) -> Result<()> {\n    let mut proxies: HashMap<String, tokio::task::JoinHandle<()>> = HashMap::new();');
const old=`            FrameKind::ExecRequest => {\n                handle_exec(&mut stream, request.stream_id, &request.payload).await?\n            }\n            FrameKind::Ping => {`;
const neu=`            FrameKind::ExecRequest => {\n                handle_exec(&mut stream, request.stream_id, &request.payload).await?\n            }\n            FrameKind::PushRequest => {\n                handle_push(&mut stream, request.stream_id, &request.payload).await?\n            }\n            FrameKind::PullRequest => {\n                handle_pull(&mut stream, request.stream_id, &request.payload).await?\n            }\n            FrameKind::ProxyStartRequest => {\n                let req: ProxyStartRequest = decode(&request.payload)?;\n                match start_proxy(&req).await {\n                    Ok((ack, task)) => {\n                        if let Some(old) = proxies.insert(req.id.clone(), task) { old.abort(); }\n                        write_frame(&mut stream, &frame(FrameKind::ProxyStartAck, request.stream_id, &ack)?).await?;\n                    }\n                    Err(error) => write_frame(&mut stream, &raw_frame(FrameKind::Error, request.stream_id, error.to_string().into_bytes())).await?,\n                }\n            }\n            FrameKind::Ping => {`;
if(!s.includes(old)) throw new Error('serve match marker missing');
s=s.replace(old,neu);
fs.writeFileSync(p,s);
