import fs from 'node:fs';
const pc='apps/sidewire/src/main.rs';
let s=fs.readFileSync(pc,'utf8');
let a=s.indexOf('async fn handle_control_pty(');
let b=s.indexOf('    loop {\n        tokio::select!',a);
let c=s.indexOf('\nasync fn process_control',b);
if(a<0||b<0||c<0) throw new Error('server PTY bridge markers missing');
const bridge=fs.readFileSync('scripts/v052-server-bridge.txt','utf8').trimEnd();
s=s.slice(0,b)+bridge+'\n}'+s.slice(c);
let p=s.indexOf('async fn run_pty_client(');
let q=s.indexOf('    let result: Result<()> = loop {',p);
let r=s.indexOf('\n}\n\nasync fn run_shell',q);
if(p<0||q<0||r<0) throw new Error('client PTY markers missing');
const client=fs.readFileSync('scripts/v052-client-loop.txt','utf8').trimEnd();
s=s.slice(0,q)+client+s.slice(r);
fs.writeFileSync(pc,s);
const daemon='apps/sidewired/src/main.rs';
let d=fs.readFileSync(daemon,'utf8');
const da=d.indexOf('async fn handle_pty(');
const db=d.indexOf('\nasync fn start_proxy',da);
if(da<0||db<0) throw new Error('daemon PTY markers missing');
const dh=fs.readFileSync('scripts/v052-daemon-handle-pty.txt','utf8').trimEnd();
d=d.slice(0,da)+dh+d.slice(db);
fs.writeFileSync(daemon,d);
