[package]
name = "sidewire"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
blake3.workspace = true
clap.workspace = true
crossterm = "0.29"
rand.workspace = true
serde.workspace = true
serde_json = "1"
sidewire-protocol = { path = "../../crates/sidewire-protocol" }
spake2.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
